### ISSUE TITLE
Multi client

### ISSUE THREAD

**Issue by svdrummer** [ameer1234567890/TelnetStream2#4]
Hello,
Is there any way this can support more than one client as Telnetstream does?
I did have the port defined as another port number, however, this causes an error
TelnetStream2.begin(10112);
changed to TelnetStream2.begin(); and it works okay

I was trying TelnetStream2 as this does not crash when a client disconnects from a server running SoftAP mode on an ESP8266 12e
Thank you

**Comment by ameer1234567890** [comment]
Try this:
```
TelnetStream2Class TelnetStream2Alt(24);

TelnetStream2Alt.begin();
```
Now you can use `TelnetStream2Alt` as the object with alternative port 24 as a second server.

**Comment by svdrummer** [comment]
Says, "Does not name a type"
